project:
  type: website
  output-dir: docs

website:
  title: "Julia MLJ"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/math4mad/Julia-MLJ
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: category/getting-started.qmd
        text: getting-stared
      - section: "Regression"
        contents:  category/regression/*.qmd
      - section: "Classfication"
        contents: category/classification/*.qmd
      - section: "Clustering"
        contents: category/clustering/*.qmd
      - section: "Dimension Reduction"
        contents: category/dimension-reduction/*.qmd
      - href: category/schedule.qmd
        text: Schedule
      - href: category/materials.qmd
        text: Materials
      - section: "Dataset Intorduction"
        contents: category/dataset/*.qmd
      

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

